### ISSUE TITLE
Auto separation occasionally causes jams

### ISSUE THREAD

**Issue by Yourself** [JGRennison/OpenTTD-patches#165] opened 2020-07-05 19:22 UTC
## Version of OpenTTD
0.34.3

## Expected result
Auto separation should evenly space trains with shared orders.

## Actual result
Sporadically vehicles (so far only noticed with trains on reasonably long routes) are kicked out of the "Timetable is running" state for no immediately apparent reason. When outside of the timetable running state vehicles are no longer visible to the auto separation algorithm which can mean that long separation times are inserted. Decreasing the auto separation adjustment percentage can mitigate some of this but causes the auto separation to be a lot less responsive.

Additionally it appears that the late timer is not reset when a vehicle leaves the timetable running state and this state transition can occur while a vehicle is waiting in a station, causing it to wait in that station until its full wait time has elapsed, potentially blocking other vehicles from using the station. This can result in a cascading failure as the auto separation only updates when any train in a shared order enters a station or waypoint. 

## Steps to reproduce
Unclear what exactly causes this, but I've seen it on timetables that are as short as 30000 ticks round trip total. I've also observed it happening independent of autofill or automate options (even with completely manually filled timetables). My initial theory was that it was a strange interaction with Maintain at Depot orders, but this seems to not be the case as leaving only proper stations in the order list still would occasionally cause this behavior.

Including frequent waypoints improves the behavior, but does not really fix it; it just gives vehicles an opportunity to re-enter the timetable running state as they pass it. I'll see if I can get a save file demonstrating this issue.

**Comment by Yourself** [comment] 2020-07-05 19:24
Oh I should have mentioned that this was observed on a multiplayer server with day length 100. However looking at the auto separation code I'm not sure the day length really matters, but at this point I'm out of ideas.

**Comment by Yourself** [comment] 2020-07-05 19:32
It occurs to me that I'm not sure if newgrfs could cause this. There is a train newgrf that seems to have some special cargo decay features in use here.

**Comment by James103** [comment] 2020-07-05 19:34
> There is a train newgrf that seems to have some special cargo decay features in use here.

What is the specific NewGRF being used and what "special cargo decay features are in use" in that NewGRF?

**Comment by Yourself** [comment] 2020-07-05 21:47
I believe it's the Southern Pacific Steam Set by ruiluth (southern_pacific_steam_set-0.6\sps_0-6.grf); GRF ID is 4A481504.

**Comment by JGRennison** [comment] 2020-07-06 11:07
Leaving the "timetable is running" state is caused by the congestion detection mechanism.
If the current travel time is > 4 times the timetabled time, it is assumed that there is a jam.
This clears the timetable started flag and separation state for all vehicles, and clears the timetabled travel time for the order which triggered the congestion detection. This is unchanged since the patch was originally written, there is definitely room for improvement.

Resetting the lateness seems like a good idea.
Re-adding vehicles to the separation one at time causing odd behaviour is also something that I hadn't thought of. I'll have a think about that. Probably group separation there will need to be held off until all the vehicles which had their separation state cleared resume separation.

NewGRFs have no effect on this. Timetabling/separation only look at the timetable and travel/wait times, it does not look at cargo.

**Comment by Yourself** [comment] 2020-07-07 04:41
It looks like the congestion check only happens when automation is enabled. I'll see if disabling automation but leaving auto separation on causes any issues to see if that's really the culprit. I'm pretty sure I've seen this happen with completely manual timetables, but that may have been a mistake on my part.

**Comment by Yourself** [comment] 2020-07-07 19:26
I've left a route running with no automation but with auto separation turned on and haven't seen the trains leave the running state which is expected, however I have seen some some notable jams (and have a save file exhibiting one). The route in question has a total round-trip time of ~90k ticks and I'm noticing that when some trains pull into a station they're getting assigned times that indicate them to be running about 42k ticks early even though they're reasonably close to trains ahead and behind. In total there's 27 vehicles so the nominal separation should be about 3300 ticks. 

I'm not entirely sure what's going on here exactly, I'm probably going to spend this week trying to create some kind of debug UI for the time table so I can see the order it thinks the trains should be in as well as their progress within the timetable to get a better idea of what might be going on.

**Comment by JGRennison** [comment] 2020-07-07 19:38
I've made a few changes which should improve things: cd89b246a7c39cac22f7c5b1bfa8e597c8b8d7b4, b7a9f9901a9f43109b9b62f42827d32ba10ff180, 3a65346abcff844148f98f3b2077daf41cd7b53e, 73340fc112fccb91f09c90f2b2ee44211fa530ec, c81c805856d7b25573360bdcf97bc2cf46963e6a.

Some of the vehicle flags related to timetabling and separation/automation are visible in the vehicle debug window. (Setting gui.newgrf_developer_tools -> on)

If you've got a savegame which is reliably problematic it might be useful if I could take a look.

**Comment by Yourself** [comment] 2020-07-08 00:40
https://drive.google.com/file/d/1xbNXcQyBFcfba917ISGh-WQuYJvn5rfy/view?usp=sharing

Here's the save I have. Also included are some extra grf's that are not on the content service.

The most problematic route is the Denver Special between Omaha and Denver. In the moment of the save there should be a rather large jam up by Lincoln. 

After manually clearing the jam by resetting the late counters, another jam happens again a few months later as well as a similar jam on the Iowa-Nebraska Limited route from Peoria to Omaha (which has automation still enabled).  It usually takes a few hours real time for these jams to manifest it seems, so it might take a good deal of patience to see them happen spontaneously.

**Comment by JGRennison** [comment] 2020-07-08 09:51
It looks like the separation order is being wrongly re-ordered when there are two trains in Lincoln North at once, such that the train behind leaves the station before the train after. The 42k ticks is half the timetable length.

**Comment by JGRennison** [comment] 2020-07-10 11:46
1f5de8b82c4e057238aaff982c7b4d3ff219e1d7 seems to significantly improve things.
Service at depot orders were indeed part of the problem.

**Comment by JGRennison** [comment] 2020-07-22 16:15
Should be fixed since 0.35.0

**Closed by JGRennison** 2020-07-22 16:15 UTC
