### ISSUE TITLE
[Bug]: Autorenew numbers player's last train incorrectly

### ISSUE THREAD

**Issue by mallardtheduck** [JGRennison/OpenTTD-patches#725] opened 2024-07-29 14:30 UTC
### Version of OpenTTD

jgrpp-0.59.1, macos

### Expected result

When autorenew (with "keep remainders" turned on) causes the player to reach their number of trains limit, the "created" trian should be numbered correctly (e.g. number 500 if the limit is 500). If possible, subsequent autorenews should display an error message to inform the player that they have reached the limit.

### Actual result

When autorenew (with "keep remainders" turned on) causes the player to reach their number of trains limit, the "created" trian is numbered 65535. No error message is displayed to inform the user that they have reached the limit.

### Steps to reproduce

1. Build limit-1 trains.
2. Set up an replacement tempalate that will change the locomotive, and has "keep remainders" turned on.
3. Apply this template to one or more of the trains in the game.
4. Note the creation of "train 65535" and no error message.

**Comment by JGRennison** [comment] 2024-08-02 20:00
This should be fixed now, the issue isn't to do with autorenew or template replacement (which is what I think you are talking about) per se, it's just to do with moving an engine out of a train to form a new train which meets the train limit.

Forwarded upstream here: https://github.com/OpenTTD/OpenTTD/pull/12887

**Closed** 2024-08-23 22:49 UTC
