### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by ruslankotl** [JGRennison/OpenTTD-patches#565] opened 2023-07-04 19:04 UTC
### Version of OpenTTD

0.54.1

### Steps to reproduce

1. Tried to extend interval between starting of competitors
2. Game Crashed

### Upload crash files

[Archive.zip](https://github.com/JGRennison/OpenTTD-patches/files/11951891/Archive.zip)

**Comment by James103** [comment] 2023-07-04 19:09
Duplicate of #548. Will you please update your JGRPP installation to 0.54.2?

**Closed** 2023-07-09 12:58 UTC
