### ISSUE TITLE
[Crash]: Reloading savegames using “New Renewed Village Growth” script (may be the problem with the script, but basically script problem would not crash the game)

### ISSUE THREAD

**Issue by JohnFranklin523** [JGRennison/OpenTTD-patches#580] opened 2023-07-30 06:32 UTC
### Version of OpenTTD

JGRPP 0.54.4, Windows 10

### Steps to reproduce

1. Download Renewed Village Growth on BaNaNaS to automatically download script library needed.
2. Download New Renewed Village Growth here, which is the script of the save game, and move it to whatever\openttd\content_download\game.
3. Download the save game here and open it.
4. Game crashes.

### Upload crash files

[crash.zip](https://github.com/JGRennison/OpenTTD-patches/files/12208620/crash.zip)

**Comment by JGRennison** [comment] 2023-07-30 10:31
It seems likely that this is caused by the use of the date cheat.
It seems that link graph job start dates were not properly updated when this occurred.
In this case the job start dates came to be before the corresponding graph's last compression date.
This will be fixed in the next release.

**Comment by JGRennison** [comment] 2023-07-30 10:46
[China Railway Beijing Group, 1965-04-23 - fix.sav.zip](https://github.com/JGRennison/OpenTTD-patches/files/12208982/China.Railway.Beijing.Group.1965-04-23.-.fix.sav.zip)

The attached file should be usable

**Comment by JGRennison** [comment] 2023-08-02 20:49
This should be fixed in the most recent release

**Closed by JGRennison** 2023-08-02 20:49 UTC
