### ISSUE TITLE
[Crash]: plus new company crash

### ISSUE THREAD

**Issue by JukjeonWani** [JGRennison/OpenTTD-patches#431] opened 2022-09-16 13:25 UTC
### Version of OpenTTD

jgrpp 0.48.2, windows 11

### Steps to reproduce

* Multi play user make new company
* crash

### Upload crash files

*** OpenTTD Crash Report ***

Crash at: 2022-09-16 13:21:05 (UTC)
In game date: 2000-01-01 (2, 0) (DL: 1)
Game loaded at: 2000-01-01 (2, 0), Fri Sep 16 13:18:39 2022

Crash reason:
 Exception:  E1212012
 Location:   00007FFC4C52474C
 Message:    Assertion failed at line 999 of /home/jgr/openttd/jgrpp/src/command.cpp: _docommand_recursive == 0

Within context:
     0: DoCommandP: tile: 0 (0 x 0), p1: 0x0, p2: 0x528A6780, p3: 0x0, company: 0 (이름 없음), cmd: 0x34 (CmdSetCompanyManagerFace), my_cmd: 1
     1: DoCommandP: tile: 0 (0 x 0), p1: 0x0, p2: 0xA, p3: 0x0, company: 0 (이름 없음), cmd: 0x15D (CmdCompanyCtrl), my_cmd: 1, text, str length: 0

Non-main thread (ottd:game)

OpenTTD version:
 Version:     jgrpp-0.48.2 (0)
 Release ver: 0.48.2
 NewGRF ver:  1d006d64
 Bits:        64
 Endian:      little
 Dedicated:   no
 Build date:  Sep  9 2022 20:48:52
 Defines:     NDEBUG WITH_BITMATH_BUILTINS WITH_OVERFLOW_BUILTINS WITH_DEMANGLE WITH_BFD0 WITH_DBGHELP TTD_ENDIAN=TTD_LITTLE_ENDIAN WITH_PNG WITH_ZLIB WITH_LIBLZMA WITH_LZO WITH_ZSTD WITH_OPENGL WITH_PERSONAL_DIR WITH_SSE WITH_ASSERT UNICODE _UNICODE WITH_UNISCRIBE PSAPI_VERSION=1 POINTER_IS_64BIT

Stack trace:
 00000000 00000000 00000016 00000000 4E329520 00007FFC 1397B9E0 00000000
 E1212012 00000080 00000000 00000000 4C52474C 00007FFC 00000000 00000000
 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 1397BAC0 00000000 4F0279E1 00007FFC 1397BAB0 00000000 05E90000 00000000
 00000001 00000000 00000000 00000000 00000000 00000000 00000000 00000000
 00000000 00000000 4D7D8668 00007FFC 00000000 00000000 00000000 00000000
 13F121E8 00004635 4D846000 00007FFC 00000000 00000000 4E2BDBF2 00007FFC
 00000016 00000000 00000030 00000003 00000016 00000000 4E329520 00007FFC
 1602E718 00000000 00000010 0000007C 4CB62634 00007FFC 06A72E00 00000000
 528A6780 00000000 1602F730 00000000 00000000 00000000 1602ED10 00000000
 00000034 00000000 4E2C20CB 00007FFC 00000001 00000000 00000001 00000000
 00000000 00000000 00000034 00000000 00000001 00000000 52EE0D56 00008D68
 00000006 00000000 000D0944 00000000 0CC873E0 00000000 000D0000 00000000
 000B0037 00000000 363FA185 00000C12 0000026A 00000000 0CC3F6C0 00000000
 0CC3FEF0 00000000 4D82B790 00007FFC 00000000 00000000 4D7B0000 00007FFC
 00000001 00000000 00000001 00000000 00000000 00000000 00000000 00000000
 0CC3FEF0 00000000 4F0279E1 00007FFC 0CC3FEE0 00000000 05E90000 00000000
 1602E909 00000000 00000000 00000000 00000000 00000000 00000001 00000000
 0CC3FEF0 00000000 4D82D9D6 00007FFC 00010007 00000000 1602EB40 00000000
 1602EB40 00000000 0CC3FEF0 00000000 1602EB40 00000000 00000000 00000000
 00000021 00000000 000001AB 00000000 00000039 00000000 25880570 00000000
 00000062 00000000 00000082 00000000 00000040 00002010 00000064 7F01FFFF
 00000039 00000028 0000001C 00007FFC 00000CD7 FFFFFFFF 0CC3FEF0 00000000
 00000013 00000000 0000032C 00000000 000001AB 00000000 00000780 00000000

Registers:
 RAX: 00007FFC4D7BE72B RBX: 0000000000000016 RCX: 000000001602DE00 RDX: 0000000000000000
 RSI: 00007FFC4E329520 RDI: 0000000000000000 RBP: 0000000000000000 RSP: 000000001602E5E0
 R8:  0000000000000000 R9:  00000000001309D4 R10: 00007FFC4F04FA59 R11: 0000000000000000
 R12: 0000000000000910 R13: 0000000000000000 R14: 00000000004F1150 R15: 0000000000000001
 RIP: 00007FFC4C52474C EFLAGS: 00000206

 Bytes at instruction pointer:
 0F 1F 44 00 00 48 8B 8C 24 C0 00 00 00 48 33 CC E8 CF B0 06 00 48 81 C4

Operating system:
 Name:     Windows
 Release:  10.0.22000 ()
 Compiler: GCC 9.3.0 "9.3-win32 20200320"

Configuration:
 Blitter:      40bpp-anim
 Graphics set: OpenGFX (7938)
 Language:     C:\Users\plmok\OneDrive\바탕 화면\openttd-jgrpp-0.48.2-windows-win64\lang\korean.lng
 Music driver: dmusic
 Music set:    OpenMSX (96)
 Network:      client
 Sound driver: win32
 Sound set:    OpenSFX (7974)
 Video driver: win32-opengl (Intel(R) UHD Graphics, 4.5.0 - Build 26.20.100.7870)
 Pathfinder:   YAPF YAPF YAPF

Fonts:
 Small:  맑은 고딕
 Medium: 맑은 고딕
 Large:  맑은 고딕
 Mono:   sprite

Map size: 0x400000 (2048 x 2048)

AI Configuration (local: 0) (current: 0):
  0: Human

Libraries:
 LZMA:       5.2.1
 ZSTD:       1.4.8
 LZO:        2.10
 PNG:        1.5.23
 Zlib:       1.2.8

Module information:
 C:\Users\plmok\OneDrive\바탕 화면\openttd-jgrpp-0.48.2-windows-win64\openttd.exe handle: 0000000000400000 size: 70568645 crc: 6C996438 date: 2022-09-12 04:08:13
 C:\WINDOWS\SYSTEM32\ntdll.dll handle: 00007ffc4f000000 size: 2129392 crc: AD144435 date: 2022-08-12 03:40:15
 C:\WINDOWS\System32\KERNEL32.DLL handle: 00007ffc4d510000 size: 786520 crc: A6CE5614 date: 2022-06-17 11:19:06
 C:\WINDOWS\System32\KERNELBASE.dll handle: 00007ffc4c4e0000 size: 3687168 crc: 9EB0ED91 date: 2022-08-12 03:40:17
 C:\WINDOWS\System32\ADVAPI32.dll handle: 00007ffc4dbd0000 size: 720368 crc: 4BC36E2C date: 2022-06-07 05:30:55
 C:\WINDOWS\System32\msvcrt.dll handle: 00007ffc4e290000 size: 673896 crc: 11D3F579 date: 2021-06-05 12:05:25
 C:\WINDOWS\System32\sechost.dll handle: 00007ffc4d270000 size: 658400 crc: 931066B2 date: 2022-06-17 11:19:14
 C:\WINDOWS\System32\RPCRT4.dll handle: 00007ffc4eea0000 size: 1195568 crc: 8F516E61 date: 2022-06-07 05:36:29
 C:\WINDOWS\System32\GDI32.dll handle: 00007ffc4d4e0000 size: 179080 crc: 30147294 date: 2022-08-12 03:40:00
 C:\WINDOWS\System32\win32u.dll handle: 00007ffc4cb60000 size: 166704 crc: 03B9C540 date: 2022-08-12 03:40:07
 C:\WINDOWS\System32\gdi32full.dll handle: 00007ffc4cc00000 size: 1150096 crc: 078699CB date: 2022-08-12 03:40:19
 C:\WINDOWS\System32\msvcp_win.dll handle: 00007ffc4c8e0000 size: 649104 crc: 33D056E0 date: 2021-06-05 12:05:23
 C:\WINDOWS\System32\ucrtbase.dll handle: 00007ffc4c980000 size: 1132544 crc: F3DDB40F date: 2021-06-05 12:05:23
 C:\WINDOWS\System32\USER32.dll handle: 00007ffc4d7b0000 size: 1778160 crc: E47629F2 date: 2022-08-12 03:40:05
 C:\WINDOWS\System32\IMM32.dll handle: 00007ffc4e3e0000 size: 211088 crc: 30F98655 date: 2021-06-05 12:05:27
 C:\WINDOWS\System32\ole32.dll handle: 00007ffc4da30000 size: 1694472 crc: 24D71B12 date: 2022-06-07 05:36:03
 C:\WINDOWS\System32\combase.dll handle: 00007ffc4cef0000 size: 3670600 crc: 09E4B9ED date: 2022-07-15 07:11:16
 C:\WINDOWS\System32\PSAPI.DLL handle: 00007ffc4dd10000 size: 41664 crc: 14228118 date: 2021-06-05 12:05:23
 C:\WINDOWS\System32\SHELL32.dll handle: 00007ffc4e6e0000 size: 8145608 crc: F0F85AEA date: 2022-08-12 03:40:20
 C:\WINDOWS\System32\WS2_32.dll handle: 00007ffc4d9c0000 size: 467296 crc: 714A995B date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\WINMM.dll handle: 00007ffc43f40000 size: 211096 crc: 7116E50C date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\OPENGL32.dll handle: 00007ffc2a4f0000 size: 937984 crc: 1A7AE606 date: 2022-06-17 11:19:39
 C:\WINDOWS\SYSTEM32\USP10.dll handle: 00007ffbeba90000 size: 102400 crc: BF045E3F date: 2021-06-05 12:05:27
 C:\WINDOWS\SYSTEM32\GLU32.dll handle: 00007ffc38030000 size: 180224 crc: 9212C533 date: 2022-06-17 11:19:39
 C:\WINDOWS\SYSTEM32\dxcore.dll handle: 00007ffc49a50000 size: 232792 crc: 9D92F799 date: 2022-06-07 05:33:32
 C:\WINDOWS\SYSTEM32\CRYPTSP.dll handle: 00007ffc4bd40000 size: 107808 crc: FBD202C8 date: 2021-06-05 12:05:23
 C:\WINDOWS\system32\rsaenh.dll handle: 00007ffc4b630000 size: 227624 crc: BD5E82DF date: 2022-06-07 05:36:15
 C:\WINDOWS\SYSTEM32\CRYPTBASE.dll handle: 00007ffc4bd60000 size: 58224 crc: 01FD7442 date: 2021-06-05 12:05:25
 C:\WINDOWS\System32\bcryptPrimitives.dll handle: 00007ffc4c860000 size: 534464 crc: 86499C20 date: 2022-07-15 07:11:20
 C:\WINDOWS\SYSTEM32\windows.storage.dll handle: 00007ffc4a560000 size: 8881104 crc: AFC23976 date: 2022-08-12 03:40:03
 C:\WINDOWS\SYSTEM32\wintypes.dll handle: 00007ffc4a3f0000 size: 1484800 crc: 65697422 date: 2022-07-15 07:11:16
 C:\WINDOWS\System32\SHCORE.dll handle: 00007ffc4d310000 size: 972432 crc: 0E624C87 date: 2022-06-07 05:34:57
 C:\WINDOWS\System32\shlwapi.dll handle: 00007ffc4e4d0000 size: 388744 crc: BF10454F date: 2021-06-05 12:05:33
 C:\WINDOWS\system32\uxtheme.dll handle: 00007ffc45df0000 size: 696320 crc: 9314217B date: 2022-08-12 03:40:08
 C:\WINDOWS\System32\MSCTF.dll handle: 00007ffc4e530000 size: 1183152 crc: D474286F date: 2022-07-15 07:11:09
 C:\WINDOWS\SYSTEM32\directxdatabasehelper.dll handle: 00007ffc41dc0000 size: 286512 crc: DFC8C66A date: 2022-06-07 05:33:31
 C:\WINDOWS\SYSTEM32\ntmarta.dll handle: 00007ffc49ac0000 size: 219352 crc: 1A189826 date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\kernel.appcore.dll handle: 00007ffc4b6d0000 size: 107784 crc: D480B782 date: 2022-06-07 05:34:02
 C:\WINDOWS\System32\clbcatq.dll handle: 00007ffc4e420000 size: 715192 crc: 35DEF128 date: 2021-06-05 12:05:23
 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_2c4f5af87c580ef1\ig9icd64.dll handle: 00007ffbb4f70000 size: 15749448 crc: 9986D5E6 date: 2020-03-03 13:56:38
 C:\WINDOWS\system32\dwmapi.dll handle: 00007ffc49c00000 size: 186304 crc: 67499569 date: 2022-06-07 05:36:06
 C:\WINDOWS\system32\dxgi.dll handle: 00007ffc45f60000 size: 1001328 crc: 24A7E2F2 date: 2022-06-17 11:18:58
 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_2c4f5af87c580ef1\igc64.dll handle: 00007ffc3b250000 size: 38781584 crc: F7644690 date: 2020-03-03 13:56:44
 C:\WINDOWS\SYSTEM32\powrprof.dll handle: 00007ffc4af00000 size: 326784 crc: 4FA0289C date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\UMPDC.dll handle: 00007ffc4afd0000 size: 87128 crc: EFBDF558 date: 2021-06-05 12:04:57
 C:\WINDOWS\System32\OLEAUT32.dll handle: 00007ffc4d400000 size: 884600 crc: DB2A5BE3 date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\textinputframework.dll handle: 00007ffc1cc70000 size: 1248208 crc: D8DC7997 date: 2022-06-07 05:33:37
 C:\WINDOWS\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_2c4f5af87c580ef1\igdgmm64.dll handle: 00007ffc3ea60000 size: 1759656 crc: 69CA919F date: 2020-03-03 13:57:04
 C:\WINDOWS\system32\mswsock.dll handle: 00007ffc4bb00000 size: 430080 crc: 02FFC4B3 date: 2021-06-05 12:05:23
 C:\WINDOWS\SYSTEM32\winmmbase.dll handle: 00007ffc38d60000 size: 173880 crc: DE915E87 date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\MMDevAPI.DLL handle: 00007ffc41f40000 size: 645984 crc: 9A566A1B date: 2022-06-17 11:18:04
 C:\WINDOWS\SYSTEM32\wdmaud.drv handle: 00007ffc30030000 size: 278528 crc: F97FFF3E date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\AVRT.dll handle: 00007ffc44360000 size: 55112 crc: 2504B8D9 date: 2022-06-07 05:30:30
 C:\WINDOWS\SYSTEM32\ksuser.dll handle: 00007ffc31020000 size: 45792 crc: 4298F33E date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\DEVOBJ.dll handle: 00007ffc4c200000 size: 190424 crc: 15617D83 date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\cfgmgr32.dll handle: 00007ffc4c1b0000 size: 318520 crc: 084BF0F1 date: 2021-06-05 12:05:25
 C:\WINDOWS\SYSTEM32\AUDIOSES.DLL handle: 00007ffc3e880000 size: 1931032 crc: 1DFDD7ED date: 2022-06-17 11:18:04
 C:\WINDOWS\SYSTEM32\msacm32.drv handle: 00007ffc44550000 size: 53248 crc: E5AB6EE9 date: 2022-06-07 05:30:24
 C:\WINDOWS\SYSTEM32\MSACM32.dll handle: 00007ffc44530000 size: 132576 crc: 5B9A077F date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\midimap.dll handle: 00007ffc3ab00000 size: 45056 crc: 19481042 date: 2021-06-05 12:04:54
 C:\WINDOWS\SYSTEM32\CoreMessaging.dll handle: 00007ffc457c0000 size: 1268888 crc: 91B0FB06 date: 2022-06-07 05:36:09
 C:\WINDOWS\System32\dmusic.dll handle: 00007ffc2fdc0000 size: 180224 crc: FBFBEF0F date: 2022-06-07 05:42:30
 C:\WINDOWS\System32\DSOUND.dll handle: 00007ffc1a1a0000 size: 655360 crc: 793CEFBE date: 2021-06-05 12:04:54
 C:\WINDOWS\System32\ResampleDmo.DLL handle: 00007ffc176f0000 size: 735848 crc: 6D1A4DAD date: 2021-06-05 18:08:21
 C:\WINDOWS\System32\msdmo.dll handle: 00007ffc36eb0000 size: 54072 crc: 601B8185 date: 2021-06-05 12:04:54
 C:\WINDOWS\System32\dmsynth.dll handle: 00007ffc1dea0000 size: 143360 crc: CC073AD2 date: 2022-06-07 05:42:30
 C:\WINDOWS\SYSTEM32\resourcepolicyclient.dll handle: 00007ffc49b00000 size: 95392 crc: 6BDC9966 date: 2021-06-05 12:05:03
 C:\Windows\System32\Windows.UI.dll handle: 00007ffc39850000 size: 1624232 crc: 96F765DF date: 2021-06-05 12:05:27
 C:\WINDOWS\SYSTEM32\TextShaping.dll handle: 00007ffc325b0000 size: 727576 crc: F36332B7 date: 2022-06-07 05:33:22
 C:\WINDOWS\SYSTEM32\CoreUIComponents.dll handle: 00007ffc41370000 size: 3603632 crc: 73109799 date: 2022-06-07 05:33:16
 C:\Windows\System32\IME\IMEKR\imkrtip.dll handle: 00007ffc1b9f0000 size: 885048 crc: 64075C76 date: 2021-06-05 12:06:59
 C:\WINDOWS\SYSTEM32\PROPSYS.dll handle: 00007ffc44770000 size: 1025096 crc: 9F1D9C81 date: 2022-06-07 05:34:01
 C:\Windows\System32\IME\shared\imetip.dll handle: 00007ffc0f910000 size: 1181032 crc: BF0827ED date: 2022-06-17 11:19:36
 C:\WINDOWS\SYSTEM32\OLEACC.dll handle: 00007ffc37120000 size: 430080 crc: 611B01CB date: 2021-06-05 12:05:39
 C:\WINDOWS\SYSTEM32\VERSION.dll handle: 00007ffc43ac0000 size: 49936 crc: B4751E63 date: 2021-06-05 12:05:33
 C:\WINDOWS\SYSTEM32\DUI70.dll handle: 00007ffc00d60000 size: 1818624 crc: 05EEDF87 date: 2021-06-05 12:05:29
 C:\Windows\System32\IME\IMEKR\imkrapi.dll handle: 00007ffc31260000 size: 299336 crc: CF32C505 date: 2021-06-05 12:06:59
 C:\WINDOWS\SYSTEM32\policymanager.dll handle: 00007ffc43320000 size: 670784 crc: F42503BF date: 2022-08-12 03:40:19
 C:\WINDOWS\SYSTEM32\msvcp110_win.dll handle: 00007ffc43270000 size: 607776 crc: DCB21A20 date: 2021-06-05 12:04:52
 C:\Windows\System32\IME\shared\imjkapi.dll handle: 00007ffc2f6d0000 size: 278848 crc: B65D9B04 date: 2021-06-05 12:06:06
 C:\WINDOWS\SYSTEM32\DNSAPI.dll handle: 00007ffc4b230000 size: 964168 crc: 8EE3A3B0 date: 2022-08-12 03:40:14
 C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL handle: 00007ffc4b200000 size: 194560 crc: F9AC787A date: 2022-06-07 05:36:11
 C:\WINDOWS\System32\NSI.dll handle: 00007ffc4e190000 size: 45824 crc: 0B41D24A date: 2021-06-05 12:05:25
 C:\Windows\System32\rasadhlp.dll handle: 00007ffc41b90000 size: 40960 crc: 31BF9F63 date: 2021-06-05 12:05:40
 C:\WINDOWS\System32\fwpuclnt.dll handle: 00007ffc41e10000 size: 528384 crc: 5EE2E20E date: 2022-06-17 11:19:03

Events: , i

---- gamelog start ----
Tick 0: new game started
Revision text changed to jgrpp-0.48.2, savegame version 292, not modified, _openttd_newgrf_version = 0x1d006d64
New game mode: 1 landscape: 0
Added NewGRF: GRF ID 544B5555, checksum 3C87268B1FAC35FE1DD55356FC2FB0F6, filename: korean_train_set-2.3.0\ko_train_set.grf (md5sum matches)
Added NewGRF: GRF ID 544B0202, checksum CFE186E5AE70F5EAE0A9A35DD725B2C8, filename: korean_bus_set-0.5.0\ko_bus_set.grf (md5sum matches)
Added NewGRF: GRF ID 544B0101, checksum B9C8E3FF005364DC0635C28A92807943, filename: korean_town_names-5.1\ko_town_names.grf (md5sum matches)
Added NewGRF: GRF ID 544B0603, checksum E7C393346303797A001EC3B408B69EAE, filename: korean_signal_set-1.2.0\ko_signal_set.grf (md5sum matches)
Added NewGRF: GRF ID 4B570001, checksum 5F3E598DAD55A07F3D518532760476C1, filename: kiwitree_station_set_part_1-1.2.1\kws_part1.grf (md5sum matches)
Added NewGRF: GRF ID 4B570002, checksum 30EACC7008D6E42398938544017D0D54, filename: kiwitree_station_set_part_2-1.2.1\kws_part2.grf (md5sum matches)
Added NewGRF: GRF ID 4A430002, checksum 93EAC5F5396584B92D4C5F0AAAF3F6C5, filename: industrial_stations_renewal-1.0.2\indstatr.grf (md5sum matches)
Added NewGRF: GRF ID 58534453, checksum 2E100BCA91DB8371CD9D57DBEC3AB0C8, filename: dutch_stations_set-1.0.0alpha\dutchstatw.grf (md5sum matches)
Added NewGRF: GRF ID 504A0110, checksum E8244C5278CB2408A818854DC11F8940, filename: dutch_station_addition_set-0.8\dstatadd_v0_8.grf (md5sum matches)
Added NewGRF: GRF ID F1250008, checksum 7440B32EC4C19BC026862D05DCD45187, filename: firs_industry_replacement_set_4-4.4.0\firs.grf (md5sum matches)
Added NewGRF: GRF ID 544D0101, checksum A03B93117C7B363F21C436781E4DF5B4, filename: 2cc_trainsinnml-3.0\2ccts.grf (md5sum matches)
Added NewGRF: GRF ID 4B475431, checksum DC3F5C2DBBD550BB43BF9E835057A65E, filename: korean_tram_set-0.3.0\korean_tram_set_0.3.0.grf (md5sum matches)
Added NewGRF: GRF ID 4B543031, checksum 30845CF0BFDE6CEC1AD498A10E1E5B9A, filename: korean_tracks-1.1.2\korean_tracks_1.1.2.grf (md5sum matches)
Added NewGRF: GRF ID 52571204, checksum 78F391DEBC824F7422A587723A0EF816, filename: egrvts2_nrt-r207\egrvts2.grf (md5sum matches)
Added NewGRF: GRF ID 414E0201, checksum 0DA3A80B986BC3C17C20CA4CE9CA26AA, filename: fish_2-2.0.3\fish.grf (md5sum matches)
Added NewGRF: GRF ID 57A50001, checksum 318F3C3F17CA68EAD533BAC88B093094, filename: was_world_airliners_set-0.1\was.grf (md5sum matches)
Added NewGRF: GRF ID 454E2001, checksum 342B064182A42854EF830BC11BE86E4E, filename: real_international_maglev_set-1.6\rims.grf (md5sum matches)
---- gamelog end ----

Recent news messages (0 of 0):

Command Log:
 Showing most recent 1 of 1 commands
   0 | 2000-01-01,  2,   0 | ----------- |        0 x       0, p1: 0x00000004, p2: 0x00000000, cc: 255, lc: 255, cmd: 0x00000145 (CmdPause)

Special Events Log:
 Showing most recent 0 of 0 events

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] KERNELBASE           0x00007FFC4C52474C RaiseException + 108
[01] msvcrt               0x00007FFC4E2BDBF2 raise + 562
[02] msvcrt               0x00007FFC4E2C20CB abort + 27
[03] openttd              0x00000000006890B6
[04] openttd              0x000000000059648F
[05] openttd              0x00000000005972D8
[06] openttd              0x000000000059C170
[07] openttd              0x00000000005962CE
[08] openttd              0x00000000005972D8
[09] openttd              0x00000000004D8830
[10] openttd              0x00000000004D6A9C
[11] openttd              0x00000000004C9BD5
[12] openttd              0x00000000006943A5
[13] openttd              0x0000000000570CE6
[14] openttd              0x0000000000570D80
[15] openttd              0x0000000000A78B94
[16] msvcrt               0x00007FFC4E2CDFB4 beginthreadex + 308
[17] msvcrt               0x00007FFC4E2CE08C endthreadex + 172
[18] KERNEL32             0x00007FFC4D5254E0 BaseThreadInitThunk + 16
[19] ntdll                0x00007FFC4F00485B RtlUserThreadStart + 43

*** End of additional info ***

**Comment by JGRennison** [comment] 2022-09-16 14:31
This is caused by https://github.com/OpenTTD/OpenTTD/issues/10016

As a workaround you can set the default company face to 0. (e.g. set player_face to 0 in openttd.cfg)

This has been fixed and will be included in the next release.

**Comment by JGRennison** [comment] 2022-09-18 13:19
Fixed in the most recent release

**Closed by JGRennison** 2022-09-18 13:19 UTC
