### ISSUE TITLE
patch Copy&Paste function?

### ISSUE THREAD

**Issue by zmarek20** [JGRennison/OpenTTD-patches#71] opened 2019-01-03 18:18 UTC
In openttd v0.29 I can not find patch copy & paste function.
https://www.tt-forums.net/viewtopic.php?f=33&t=45488

**Comment by letharion** [comment] 2019-01-03 21:58
Duplicate of https://github.com/JGRennison/OpenTTD-patches/issues/33

**Closed** 2019-02-22 17:50 UTC
