### ISSUE TITLE
A lot of desync errors

### ISSUE THREAD

**Issue by telk5093** [JGRennison/OpenTTD-patches#89] opened 2019-05-14 19:09 UTC
## Version of OpenTTD
0.31.0

## Expected result
No desync error messages in (dedicated) console when enter ```debug_level desync=1```

## Actual result
```
dbg: [desync] sync: date{000b71c5; 00; 00}; f6aa50fb; 77d148e7
dbg: [desync] sync: date{000b71c6; 00; 00}; b74febc3; c1c4039c
dbg: [desync] sync: date{000b71c7; 00; 00}; 7bd4ea92; 8799631f
dbg: [desync] sync: date{000b71c8; 00; 00}; 09c2a9d2; 6ea69b36
dbg: [desync] sync: date{000b71c9; 00; 00}; 456780a3; 8ec6f66b
dbg: [desync] sync: date{000b71ca; 00; 00}; 3f48aa77; 674c1bda
dbg: [desync] sync: date{000b71cb; 00; 00}; 0f2faacc; d6aa8cbe
dbg: [desync] sync: date{000b71cc; 00; 00}; 40752926; 4eff0017
dbg: [desync] sync: date{000b71cd; 00; 00}; d833bccf; 8ae82fb6
dbg: [desync] sync: date{000b71ce; 00; 00}; dbd8c785; aca20495
(...)
dbg: [desync] sync: date{000b7366; 00; 00}; 6a6c4ac6; a5097c21
dbg: [desync] sync: date{000b7367; 00; 00}; f885da4d; 5c08cba8
dbg: [desync] sync: date{000b7368; 00; 00}; 57f6d646; e705c868
dbg: [desync] sync: date{000b7369; 00; 00}; 46a75ec3; 89abf9da
dbg: [desync] sync: date{000b736a; 00; 00}; 88cce53c; c4e786ad
dbg: [desync] sync: date{000b736b; 00; 00}; 1bca284e; 1fa26fa1
dbg: [desync] sync: date{000b736c; 00; 00}; 1abd5f95; 206ff0fe
dbg: [desync] sync: date{000b736d; 00; 00}; 9b01a3e1; b2c7345b
(...)
```

## Steps to reproduce
1. Open any dedicated server with blank map in Linux terminal. (eg) ```./openttd -D```
2. Type ```debug_level desync=1```
3. See what console writes.

## Comments
My dedicated server```(server.telk.kr:3980)``` which using JGRPP 0.31.0 recently has returned desync errors to some clients (not to all of them) about 3~5 seconds later, after they joinned the server.

1. It isn't happened in stable(1.9.1) server, only occurs on the JGRPP server.
2. I thought first that it is about my server's CPU spec since my server's CPU is _Celeron N2807_ and it has very low performances.
 However, the desync messages are also occured in **another** server whose cpu is _Xeon E3-1230_, which has very high performances.

I've checked also in jgrpp-0.27.x and it was the same.

(Maybe it could be not only issue reporting but also help)

**Comment by JGRennison** [comment] 2019-05-14 19:26
The log output you posted is what is expected when debug level desync is 1, it does not indicate any problem.
If there are other, different warnings/errors when running with desync logging enabled, those could be useful.
I can't access your server as it is password-protected, if you could post/send a savegame of the server state I can see if the issue can be reproduced on my machine.
The CPU speed shouldn't really make any difference.

**Comment by telk5093** [comment] 2019-05-14 19:31
[dmp_cmds_41a9c63f_000b71c0.zip](https://github.com/JGRennison/OpenTTD-patches/files/3179484/dmp_cmds_41a9c63f_000b71c0.zip)
Here is dump save file (created by debug_level command), which also occurs desync error.
I have no idea when desync error occurs, but it seems not right after when server is opened.
(All contained NewGRFs are downloadable from online contents)

**Comment by JGRennison** [comment] 2019-05-31 12:41
Could you try with v0.31.1, this has various changes/fixes which should help with this.

**Comment by telk5093** [comment] 2019-06-06 07:40
Now it generates lots of desync files in root.
These are one of desync files:
[desync-server-20190606T072700Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/3260455/desync-server-20190606T072700Z.zip)
[desync-server-20190606T072700Z.sav.zip](https://github.com/JGRennison/OpenTTD-patches/files/3260459/desync-server-20190606T072700Z.sav.zip)
(And its time in file name seems to be based on UTF+0, not local. If you intented it, don't mind)

**Comment by JGRennison** [comment] 2019-06-13 20:40
I've not yet been able to find a definitive cause, and not yet been able to reproduce any desync here.
Are these still occurring regularly?
Have you or any of the other players noticed a particular pattern (e.g. problems start after a particular operation is performed, or event in-game)?
A sample of more desync logs might prove helpful, if you don't mind.
Many thanks.

**Comment by telk5093** [comment] 2019-06-14 17:47
Yes, it still generates lots of desync file in root, and I have no idea what players did.
I can't sure but I noticed and experienced desync errors (with no file outputs) since 0.31.0
Desync errors with file outputs is occured since 0.31.1.

Here's more desync logs, which is from my dedicated jgrpp server
(server.telk.kr:3980 / password is ``민국``, if you want to check out)
[desync.txt.zip](https://github.com/JGRennison/OpenTTD-patches/files/3291643/desync.txt.zip)
[desync.sav.zip](https://server.telk.kr/ottd/desync.sav.zip (62.9MiB))

**Comment by JGRennison** [comment] 2019-06-14 20:03
Thanks, these new log files contain a strong indicator of the source of the issue, hopefully this will be fixed soonish.

**Comment by JGRennison** [comment] 2019-06-16 10:15
If you switch "Company stations can serve industries with attached neutral stations" (역이 붙어 있는 산업 시설의 화물을 회사의 역이 취급 가능) to off, does that improve matters?

**Comment by telk5093** [comment] 2019-06-16 17:31
> If you switch "Company stations can serve industries with attached neutral stations" (역이 붙어 있는 산업 시설의 화물을 회사의 역이 취급 가능) to off, does that improve matters?
I have turned the config just before, need to take a look for a while if the game generates desync files or not. I'll mention you again about 1~2 days later. Thanks

**Comment by telk5093** [comment] 2019-06-18 11:34
[desync-server-20190617T032944Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/3301286/desync-server-20190617T032944Z.zip)
@JGRennison No additional desync errors except for this but I have no idea whether the config you mentioned above is turned off or not. I think it solves my issues.

**Comment by JGRennison** [comment] 2019-06-18 12:23
From the savegame it looks like the setting is still switched on, and the log suggests that it is the same issue as previously.
I will presume that this is the only source of desyncs and do another release later today.

**Comment by telk5093** [comment] 2019-07-15 15:22
Sorry for again.
Now desync errors are generated again even if I definitely have turned off ``serve_neutral_industries=off``:

See [desync-server-20190715T085621Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/3392933/desync-server-20190715T085621Z.zip)
(+ Do you need only *.log file?)

**Comment by JGRennison** [comment] 2019-07-16 21:44
If you have more log files they might be helpful.
Did you do any testing on v0.31.2 as well, and if so did you have any issues there?

**Comment by telk5093** [comment] 2019-07-17 02:38
The last log file I attached was from v0.31.3
(And note that there is no other inconvenience to use multiplay)

**Comment by telk5093** [comment] 2019-07-18 06:50
[desync-server.zip](https://github.com/JGRennison/OpenTTD-patches/files/3405126/desync-server.zip)
Additional log files, I hope it may help you

**Comment by telk5093** [comment] 2019-07-30 16:01
[2019-07-31.zip](https://github.com/JGRennison/OpenTTD-patches/files/3447636/2019-07-31.zip)
Additional logs, which is from the other physical server with the same config.

**Comment by JGRennison** [comment] 2019-12-04 20:51
Have there been any more desync issues lately? Hopefully this can be closed?

**Comment by telk5093** [comment] 2019-12-08 05:42
Unfortunately not. Game generates additional desync error files: [desync-server-20191208T034028Z.zip](https://github.com/JGRennison/OpenTTD-patches/files/3935896/desync-server-20191208T034028Z.zip)
I zipped one savefile, and three log files.

**Comment by JGRennison** [comment] 2019-12-08 12:38
I found an issue where removing tram road stops incorrectly updates the tram infrastructure total.
This looks like it could be the culprit as the tram infrastructure total is below the correct value in all 3 of the logs you posted.

See also: https://github.com/OpenTTD/OpenTTD/pull/7856

**Comment by James103** [comment] 2021-01-02 22:18
@telk5093 Have you been getting any desync errors lately? Is this issue still relevant to them? If not, this can be closed.

**Comment by telk5093** [comment] 2021-01-03 03:04
@James103 It has been reduced. But desync log file is generated on and off.

**Comment by James103** [comment] 2021-01-03 03:33
Can you post the desync errors (here or in a new issue)?

**Comment by telk5093** [comment] 2021-01-03 04:38
I will when desync file is generated again, I deleted the only desync files just yesterday 😅

**Comment by James103** [comment] 2021-11-14 10:27
@telk5093 Is this issue still relevant? In other words, are you still getting any desync errors lately?
If so, will you please post the corresponding log files?

**Comment by telk5093** [comment] 2021-11-14 10:46
@James103 Maybe not, but my dedicated server still generates some desync file sometimes, for example, 2021-10-23, 2021-20-24 (I think it is occured at jgrpp-0.43.x, not 0.44.0)
This issue could be closed since I think the desync files I mentioned in this comment is not relavant to this issue.

**Comment by James103** [comment] 2021-11-15 02:35
@telk5093 Therefore, will you please close this issue as resolved and post the desync files in a new issue if you still have them (or newer versions)?

**Closed** 2021-11-15 02:37 UTC
