### ISSUE TITLE
Crashed during saving

### ISSUE THREAD

**Issue by Hyckor** [JGRennison/OpenTTD-patches#409] opened 2022-08-06 16:42 UTC
### Version of OpenTTD

ver. 0.48.1, Win 7 and Win 11

### Steps to reproduce

The game usually crashed during saving. Sometimes, it gives message: Game save failed. Internal error: cannot initialize compressor (screenshot 2). After this message, the game sometimes continues, but it is impossible to save it - the same message repeated. The screenshots 1 and 3 show messages after several attempts to save it - Out of memory. Cannot allocate XXXXXXX bytes.
The game runs and crashes on older laptop - Win 7 and also on newly-bought desktop - Win11.
The version is 0.48.1, but it crashes also in version 0.45 and 0.48.

Memory issue?  I reduced all necessary programs, but this is not the issue, probably.  I tried to play and save it on very fast desktop bought in 2021. I suspect Newgamegrfs adding in-game???
possible queries:
How much RAM does your newer desktop have? If that's less than 8 GB, then you may need to upgrade the RAM to at least that amount, or more if possible. Try checking both the Processes and Performance tabs in Task Manager while playing and watch for any spikes in RAM usage.
This is not the issue. I played the same map file and same world a month ago with no problems. I played the same own-built world map 10-12 years in a row - systematically building the traffic infrastructure a fleets of planes, trains other vehicles. 
During last weeks when the issue appears, I reduced all WIN visual effects, aero effects, all unnecessary programs in a background and startup features to a minimum for saving memory. I increased the virtual memory, but this is not a problem I guess. My new desktop is so fast for that game, so I made an experiment and played a while the several most recent savegames (the game runs too fast - I do not like this fast machine), but it crashed in a same manner. I do not know how much RAM it has and I will able to check it Monday (not at home during weekend), but there are memory-consuming FPS working fine. I accidentally closed the issue ticket, so here is repeatedly posted.
![183252913-db5cd67d-8811-4214-b987-c55cdae3ceeb](https://user-images.githubusercontent.com/110730170/183258134-b50c6814-be35-4a3e-90e0-b1282c4b806b.jpg)
![183252915-d5521dc5-a79d-453b-8f05-79d8bb5aa657](https://user-images.githubusercontent.com/110730170/183258136-eb565409-e12d-4a6f-8cfd-6c1e6efbe115.jpg)
![183252917-7c686be6-3a9c-4334-839b-91ab9723c7ce](https://user-images.githubusercontent.com/110730170/183258138-0a287241-f792-4b9e-a605-824aa240e139.jpg)
 

### Upload crash files

[OpenTTD.zip](https://github.com/JGRennison/OpenTTD-patches/files/9275441/OpenTTD.zip)

**Comment by JGRennison** [comment] 2022-08-06 18:13
Duplicate of #408

**Closed by JGRennison** 2022-08-06 18:13 UTC
